# Generated by Django 2.1.2 on 2018-11-04 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 4, 23, 41, 15, 376907), verbose_name='订单生成时间'),
        ),
    ]
